services:
  dcss:
    image: dcss-server:latest
    tty: true
    stdin_open: true
    entrypoint: /docker-entrypoint.sh
    build:
      context: ../
      dockerfile: server/Dockerfile
    ports:
      - ":8080"
      - ":22"
      - ":80"
    volumes:
      - ./data/versionsdb:/versionsdb
      - ./data/crawl-master:/crawl-master
      - ./data/dgldir:/dgldir
      - ./data/usr-games:/usr/games
      - ./data/ccache:/root/.cache/ccache
