name: build-all

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 16384
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-docker-images: 'true'
        remove-codeql: 'true'

    - uses: actions/checkout@v2

    - name: Docker container test
      run: |
        cd server
        ./download-ccache.sh
        cp docker-compose.build-all.yml docker-compose.override.yml
        docker-compose up
