name: build-all

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Free unused disk space
      shell: bash
      run: |
        # ref. https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh#L28-L53
        # delete packages
             sudo apt-get remove -y '^dotnet-.*'
             sudo apt-get remove -y '^llvm-.*'
             sudo apt-get remove -y '^temurin-.*'
             sudo apt-get remove -y '^mysql-server-core-.*'
             sudo apt-get remove -y '^postgresql-.*'
             sudo apt-get remove -y azure-cli google-chrome-stable google-cloud-cli firefox powershell microsoft-edge-stable mono-devel
             sudo apt-get autoremove -y
             sudo apt-get clean
        
        # delete directories
             sudo rm -rf /usr/share/dotnet/
             sudo rm -rf /usr/share/swift
             sudo rm -rf /usr/share/miniconda
             sudo rm -rf /usr/local/graalvm/
             sudo rm -rf /usr/local/.ghcup/
             sudo rm -rf /usr/local/share/powershell
             sudo rm -rf /usr/local/share/chromium
             sudo rm -rf /usr/local/lib/android
             sudo rm -rf /usr/local/lib/node_modules

    - name: Docker container test
      run: |
        cd server
        ./download-ccache.sh
        cp docker-compose.build-all.yml docker-compose.override.yml
        docker-compose up
