name: build-trunk

on:
  push:
    branches: [ master, develop, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download ccache
        run: |
          ./download-ccache.sh
        working-directory: server

      - name: Build test
        run: |
          ONLY_BUILD=true COMMAND=build-trunk docker-compose up 2>&1 | tee docker-compose.log
        working-directory: server

      - name: Print result
        run: |
          grep -B 100 -A 3 -e "Error 1" -e "\[fail\]" docker-compose.log || true
          ls data/crawl-master | xargs
          ! grep -q -e "Error 1" -e "\[fail\]" docker-compose.log
        working-directory: server
