name: build-trunk

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v2

    - name: Build test
      run: |
        cd server
        ./download-ccache.sh
        cp docker-compose.build-trunk.yml docker-compose.override.yml
        docker-compose up -d
        ( docker-compose logs -f | awk '/Starting webtiles server webtiles/ {matched=1; start_time=systime();} matched && systime() - start_time >= 10 {exit} !matched {print} ' )
        ls data/crawl-master
