name: build-all

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker container test
      run: |
        cd server
        sed -i 's|entrypoint:.*|entrypoint: /docker-entrypoint-build-all.sh|' docker-compose.yaml
        docker-compose up
