name: upload-ccache

on:
  push:
    branches: [ upload-ccache ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build & upload
      run: |
        cd server
        ./download-ccache.sh
        cp docker-compose.build-all.yml docker-compose.override.yml
        docker-compose up -d
        sleep 18000
        ./upload-ccache.sh "build-ccache (from Action)"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
